/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AcceptFinancialOffer
 * @category generated
 */
export type AcceptFinancialOfferInstructionArgs = {
  amountToBuy: beet.bignum
}
/**
 * @category Instructions
 * @category AcceptFinancialOffer
 * @category generated
 */
export const acceptFinancialOfferStruct = new beet.BeetArgsStruct<
  AcceptFinancialOfferInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amountToBuy', beet.u64],
  ],
  'AcceptFinancialOfferInstructionArgs',
)
/**
 * Accounts required by the _acceptFinancialOffer_ instruction
 *
 * @property [] clubData
 * @property [] memberData
 * @property [_writable_, **signer**] payer
 * @property [_writable_] seller
 * @property [_writable_] financialOffer
 * @property [_writable_] treasuryData
 * @property [] treasury
 * @property [_writable_] buyerFinancialRecord
 * @property [_writable_] sellerFinancialRecord
 * @category Instructions
 * @category AcceptFinancialOffer
 * @category generated
 */
export type AcceptFinancialOfferInstructionAccounts = {
  clubData: web3.PublicKey
  memberData: web3.PublicKey
  payer: web3.PublicKey
  seller: web3.PublicKey
  financialOffer: web3.PublicKey
  treasuryData: web3.PublicKey
  treasury: web3.PublicKey
  buyerFinancialRecord: web3.PublicKey
  sellerFinancialRecord: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const acceptFinancialOfferInstructionDiscriminator = [
  224, 174, 6, 50, 253, 49, 64, 103,
]

/**
 * Creates a _AcceptFinancialOffer_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AcceptFinancialOffer
 * @category generated
 */
export function createAcceptFinancialOfferInstruction(
  accounts: AcceptFinancialOfferInstructionAccounts,
  args: AcceptFinancialOfferInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = acceptFinancialOfferStruct.serialize({
    instructionDiscriminator: acceptFinancialOfferInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.seller,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.financialOffer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerFinancialRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.sellerFinancialRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
