/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AddCanLeaveAction
 * @category generated
 */
export const addCanLeaveActionStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'AddCanLeaveActionInstructionArgs',
)
/**
 * Accounts required by the _addCanLeaveAction_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] clubData
 * @category Instructions
 * @category AddCanLeaveAction
 * @category generated
 */
export type AddCanLeaveActionInstructionAccounts = {
  payer: web3.PublicKey
  clubData: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addCanLeaveActionInstructionDiscriminator = [
  119, 204, 179, 154, 183, 172, 200, 100,
]

/**
 * Creates a _AddCanLeaveAction_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category AddCanLeaveAction
 * @category generated
 */
export function createAddCanLeaveActionInstruction(
  accounts: AddCanLeaveActionInstructionAccounts,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = addCanLeaveActionStruct.serialize({
    instructionDiscriminator: addCanLeaveActionInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.clubData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
