/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  SellPermissionDto,
  sellPermissionDtoBeet,
} from '../types/SellPermissionDto.js'

/**
 * @category Instructions
 * @category AddSellPermission
 * @category generated
 */
export type AddSellPermissionInstructionArgs = {
  maxVotingTime: number
  sellPermissionConfig: SellPermissionDto
}
/**
 * @category Instructions
 * @category AddSellPermission
 * @category generated
 */
export const addSellPermissionStruct = new beet.BeetArgsStruct<
  AddSellPermissionInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['maxVotingTime', beet.u32],
    ['sellPermissionConfig', sellPermissionDtoBeet],
  ],
  'AddSellPermissionInstructionArgs',
)
/**
 * Accounts required by the _addSellPermission_ instruction
 *
 * @property [] splGovernanceProgram
 * @property [] realm
 * @property [_writable_] realmConfig
 * @property [**signer**] realmAuthority
 * @property [_writable_, **signer**] payer
 * @property [_writable_] tokenOwnerRecord
 * @property [_writable_] governance
 * @property [_writable_] governedSpc
 * @property [_writable_] voterWeightRecord
 * @property [] treasury
 * @property [_writable_] treasuryData
 * @property [] memberData
 * @property [] clubData
 * @category Instructions
 * @category AddSellPermission
 * @category generated
 */
export type AddSellPermissionInstructionAccounts = {
  splGovernanceProgram: web3.PublicKey
  realm: web3.PublicKey
  realmConfig: web3.PublicKey
  realmAuthority: web3.PublicKey
  payer: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  governance: web3.PublicKey
  governedSpc: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  memberData: web3.PublicKey
  clubData: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addSellPermissionInstructionDiscriminator = [
  31, 3, 191, 151, 142, 130, 51, 45,
]

/**
 * Creates a _AddSellPermission_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddSellPermission
 * @category generated
 */
export function createAddSellPermissionInstruction(
  accounts: AddSellPermissionInstructionAccounts,
  args: AddSellPermissionInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = addSellPermissionStruct.serialize({
    instructionDiscriminator: addSellPermissionInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.realmConfig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realmAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governedSpc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
