/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category AddStakeConfigToStakeRecord
 * @category generated
 */
export const addStakeConfigToStakeRecordStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'AddStakeConfigToStakeRecordInstructionArgs',
)
/**
 * Accounts required by the _addStakeConfigToStakeRecord_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] stakeRecord
 * @property [] stakeConfig
 * @category Instructions
 * @category AddStakeConfigToStakeRecord
 * @category generated
 */
export type AddStakeConfigToStakeRecordInstructionAccounts = {
  payer: web3.PublicKey
  stakeRecord: web3.PublicKey
  stakeConfig: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addStakeConfigToStakeRecordInstructionDiscriminator = [
  222, 215, 186, 152, 85, 73, 61, 243,
]

/**
 * Creates a _AddStakeConfigToStakeRecord_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category AddStakeConfigToStakeRecord
 * @category generated
 */
export function createAddStakeConfigToStakeRecordInstruction(
  accounts: AddStakeConfigToStakeRecordInstructionAccounts,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = addStakeConfigToStakeRecordStruct.serialize({
    instructionDiscriminator:
      addStakeConfigToStakeRecordInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.stakeRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.stakeConfig,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
