/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CancelSolseaOffer
 * @category generated
 */
export type CancelSolseaOfferInstructionArgs = {
  chainId: string
}
/**
 * @category Instructions
 * @category CancelSolseaOffer
 * @category generated
 */
export const cancelSolseaOfferStruct = new beet.FixableBeetArgsStruct<
  CancelSolseaOfferInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['chainId', beet.utf8String],
  ],
  'CancelSolseaOfferInstructionArgs',
)
/**
 * Accounts required by the _cancelSolseaOffer_ instruction
 *
 * @property [] clubData
 * @property [_writable_] solseaEscrow
 * @property [_writable_] solseaEscrowTokens
 * @property [] offeredTokenMint
 * @property [_writable_] solseaAuthority
 * @property [] proposal
 * @property [] treasury
 * @property [_writable_] offer
 * @property [_writable_] vault
 * @property [_writable_] makerOfferedTokens
 * @property [_writable_, **signer**] payer
 * @property [] memberData
 * @property [] escrowProgram
 * @property [] solseaProgram
 * @category Instructions
 * @category CancelSolseaOffer
 * @category generated
 */
export type CancelSolseaOfferInstructionAccounts = {
  clubData: web3.PublicKey
  solseaEscrow: web3.PublicKey
  solseaEscrowTokens: web3.PublicKey
  offeredTokenMint: web3.PublicKey
  solseaAuthority: web3.PublicKey
  proposal: web3.PublicKey
  treasury: web3.PublicKey
  offer: web3.PublicKey
  vault: web3.PublicKey
  makerOfferedTokens: web3.PublicKey
  payer: web3.PublicKey
  memberData: web3.PublicKey
  escrowProgram: web3.PublicKey
  solseaProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const cancelSolseaOfferInstructionDiscriminator = [
  186, 102, 106, 219, 253, 51, 84, 195,
]

/**
 * Creates a _CancelSolseaOffer_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CancelSolseaOffer
 * @category generated
 */
export function createCancelSolseaOfferInstruction(
  accounts: CancelSolseaOfferInstructionAccounts,
  args: CancelSolseaOfferInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = cancelSolseaOfferStruct.serialize({
    instructionDiscriminator: cancelSolseaOfferInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.solseaEscrow,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.solseaEscrowTokens,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.offeredTokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.solseaAuthority,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.offer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.makerOfferedTokens,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.escrowProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.solseaProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
