/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { ProposalAction, proposalActionBeet } from '../types/ProposalAction.js'

/**
 * @category Instructions
 * @category CancelProposal
 * @category generated
 */
export type CancelProposalInstructionArgs = {
  chainId: string
  action: ProposalAction
}
/**
 * @category Instructions
 * @category CancelProposal
 * @category generated
 */
export const cancelProposalStruct = new beet.FixableBeetArgsStruct<
  CancelProposalInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['chainId', beet.utf8String],
    ['action', proposalActionBeet],
  ],
  'CancelProposalInstructionArgs',
)
/**
 * Accounts required by the _cancelProposal_ instruction
 *
 * @property [] clubData
 * @property [] memberData
 * @property [_writable_] offer
 * @property [_writable_] proposalMetadata
 * @property [_writable_] vault
 * @property [_writable_] treasury
 * @property [] treasuryData
 * @property [_writable_] makerOfferedTokens
 * @property [_writable_, **signer**] payer
 * @property [] escrowProgram
 * @category Instructions
 * @category CancelProposal
 * @category generated
 */
export type CancelProposalInstructionAccounts = {
  clubData: web3.PublicKey
  memberData: web3.PublicKey
  offer: web3.PublicKey
  proposalMetadata: web3.PublicKey
  vault: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  makerOfferedTokens: web3.PublicKey
  payer: web3.PublicKey
  escrowProgram: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const cancelProposalInstructionDiscriminator = [
  106, 74, 128, 146, 19, 65, 39, 23,
]

/**
 * Creates a _CancelProposal_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CancelProposal
 * @category generated
 */
export function createCancelProposalInstruction(
  accounts: CancelProposalInstructionAccounts,
  args: CancelProposalInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = cancelProposalStruct.serialize({
    instructionDiscriminator: cancelProposalInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.offer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.makerOfferedTokens,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.escrowProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
