/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateChangeClubConfigGovernance
 * @category generated
 */
export type CreateChangeClubConfigGovernanceInstructionArgs = {
  voteThreshold: number
  maxVotingTime: number
}
/**
 * @category Instructions
 * @category CreateChangeClubConfigGovernance
 * @category generated
 */
export const createChangeClubConfigGovernanceStruct = new beet.BeetArgsStruct<
  CreateChangeClubConfigGovernanceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['voteThreshold', beet.u8],
    ['maxVotingTime', beet.u32],
  ],
  'CreateChangeClubConfigGovernanceInstructionArgs',
)
/**
 * Accounts required by the _createChangeClubConfigGovernance_ instruction
 *
 * @property [] realm
 * @property [] clubData
 * @property [_writable_, **signer**] payer
 * @property [] memberData
 * @property [] treasury
 * @property [_writable_] treasuryData
 * @property [_writable_] governance
 * @property [] realmConfig
 * @property [] realmAuthority
 * @property [] voterWeightRecord
 * @property [] tokenOwnerRecord
 * @property [_writable_] goverenedAccount
 * @property [] splGovernanceProgram
 * @category Instructions
 * @category CreateChangeClubConfigGovernance
 * @category generated
 */
export type CreateChangeClubConfigGovernanceInstructionAccounts = {
  realm: web3.PublicKey
  clubData: web3.PublicKey
  payer: web3.PublicKey
  memberData: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  governance: web3.PublicKey
  realmConfig: web3.PublicKey
  realmAuthority: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  goverenedAccount: web3.PublicKey
  splGovernanceProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createChangeClubConfigGovernanceInstructionDiscriminator = [
  25, 38, 116, 195, 251, 87, 22, 81,
]

/**
 * Creates a _CreateChangeClubConfigGovernance_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateChangeClubConfigGovernance
 * @category generated
 */
export function createCreateChangeClubConfigGovernanceInstruction(
  accounts: CreateChangeClubConfigGovernanceInstructionAccounts,
  args: CreateChangeClubConfigGovernanceInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = createChangeClubConfigGovernanceStruct.serialize({
    instructionDiscriminator:
      createChangeClubConfigGovernanceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.realm,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realmConfig,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.realmAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.goverenedAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
