/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateProposalMetadata
 * @category generated
 */
export type CreateProposalMetadataInstructionArgs = {
  proposalType: number
  data1: beet.COption<Uint8Array>
  data2: beet.COption<Uint8Array>
  data3: beet.COption<Uint8Array>
}
/**
 * @category Instructions
 * @category CreateProposalMetadata
 * @category generated
 */
export const createProposalMetadataStruct = new beet.FixableBeetArgsStruct<
  CreateProposalMetadataInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['proposalType', beet.u8],
    ['data1', beet.coption(beet.bytes)],
    ['data2', beet.coption(beet.bytes)],
    ['data3', beet.coption(beet.bytes)],
  ],
  'CreateProposalMetadataInstructionArgs',
)
/**
 * Accounts required by the _createProposalMetadata_ instruction
 *
 * @property [] realm
 * @property [] clubData
 * @property [] proposal
 * @property [_writable_] proposalMetadata
 * @property [] memberData
 * @property [] governance
 * @property [_writable_, **signer**] payer
 * @property [] treasuryData
 * @category Instructions
 * @category CreateProposalMetadata
 * @category generated
 */
export type CreateProposalMetadataInstructionAccounts = {
  realm: web3.PublicKey
  clubData: web3.PublicKey
  proposal: web3.PublicKey
  proposalMetadata: web3.PublicKey
  memberData: web3.PublicKey
  governance: web3.PublicKey
  payer: web3.PublicKey
  treasuryData: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createProposalMetadataInstructionDiscriminator = [
  138, 166, 66, 203, 38, 202, 18, 45,
]

/**
 * Creates a _CreateProposalMetadata_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateProposalMetadata
 * @category generated
 */
export function createCreateProposalMetadataInstruction(
  accounts: CreateProposalMetadataInstructionAccounts,
  args: CreateProposalMetadataInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = createProposalMetadataStruct.serialize({
    instructionDiscriminator: createProposalMetadataInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.realm,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.governance,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
