/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateTransferGovernance
 * @category generated
 */
export type CreateTransferGovernanceInstructionArgs = {
  maxVotingTime: number
  voteThresholdPercentage: number
}
/**
 * @category Instructions
 * @category CreateTransferGovernance
 * @category generated
 */
export const createTransferGovernanceStruct = new beet.BeetArgsStruct<
  CreateTransferGovernanceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['maxVotingTime', beet.u32],
    ['voteThresholdPercentage', beet.u8],
  ],
  'CreateTransferGovernanceInstructionArgs',
)
/**
 * Accounts required by the _createTransferGovernance_ instruction
 *
 * @property [] splGovernanceProgram
 * @property [_writable_] realm
 * @property [_writable_] realmConfig
 * @property [_writable_, **signer**] realmAuthority
 * @property [_writable_, **signer**] payer
 * @property [_writable_] tokenOwnerRecord
 * @property [_writable_] governance
 * @property [_writable_] voterWeightRecord
 * @property [] treasury
 * @property [_writable_] treasuryData
 * @property [] memberData
 * @property [_writable_] clubData
 * @property [] governedAccount
 * @category Instructions
 * @category CreateTransferGovernance
 * @category generated
 */
export type CreateTransferGovernanceInstructionAccounts = {
  splGovernanceProgram: web3.PublicKey
  realm: web3.PublicKey
  realmConfig: web3.PublicKey
  realmAuthority: web3.PublicKey
  payer: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  governance: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  memberData: web3.PublicKey
  clubData: web3.PublicKey
  governedAccount: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createTransferGovernanceInstructionDiscriminator = [
  178, 176, 246, 96, 10, 50, 161, 60,
]

/**
 * Creates a _CreateTransferGovernance_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateTransferGovernance
 * @category generated
 */
export function createCreateTransferGovernanceInstruction(
  accounts: CreateTransferGovernanceInstructionAccounts,
  args: CreateTransferGovernanceInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = createTransferGovernanceStruct.serialize({
    instructionDiscriminator: createTransferGovernanceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realmConfig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realmAuthority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governedAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
