/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  SellPermissionDto,
  sellPermissionDtoBeet,
} from '../types/SellPermissionDto.js'

/**
 * @category Instructions
 * @category CreateTreasuryGovernance
 * @category generated
 */
export type CreateTreasuryGovernanceInstructionArgs = {
  maxVotingTime: number
  voteThresholdPercentage: number
  sellPermissionConfig: SellPermissionDto[]
  nftMaxVoterWeight: beet.COption<beet.bignum>
}
/**
 * @category Instructions
 * @category CreateTreasuryGovernance
 * @category generated
 */
export const createTreasuryGovernanceStruct = new beet.FixableBeetArgsStruct<
  CreateTreasuryGovernanceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['maxVotingTime', beet.u32],
    ['voteThresholdPercentage', beet.u8],
    ['sellPermissionConfig', beet.array(sellPermissionDtoBeet)],
    ['nftMaxVoterWeight', beet.coption(beet.u64)],
  ],
  'CreateTreasuryGovernanceInstructionArgs',
)
/**
 * Accounts required by the _createTreasuryGovernance_ instruction
 *
 * @property [] splGovernanceProgram
 * @property [] realm
 * @property [_writable_] realmConfig
 * @property [**signer**] realmAuthority
 * @property [_writable_, **signer**] payer
 * @property [_writable_] tokenOwnerRecord
 * @property [_writable_] governance
 * @property [_writable_] voterWeightRecord
 * @property [_writable_] treasury
 * @property [_writable_] profit
 * @property [_writable_] treasuryData
 * @property [] memberData
 * @property [_writable_] clubData
 * @category Instructions
 * @category CreateTreasuryGovernance
 * @category generated
 */
export type CreateTreasuryGovernanceInstructionAccounts = {
  splGovernanceProgram: web3.PublicKey
  realm: web3.PublicKey
  realmConfig: web3.PublicKey
  realmAuthority: web3.PublicKey
  payer: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  governance: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  treasury: web3.PublicKey
  profit: web3.PublicKey
  treasuryData: web3.PublicKey
  memberData: web3.PublicKey
  clubData: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createTreasuryGovernanceInstructionDiscriminator = [
  247, 162, 244, 126, 115, 208, 121, 34,
]

/**
 * Creates a _CreateTreasuryGovernance_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateTreasuryGovernance
 * @category generated
 */
export function createCreateTreasuryGovernanceInstruction(
  accounts: CreateTreasuryGovernanceInstructionAccounts,
  args: CreateTreasuryGovernanceInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = createTreasuryGovernanceStruct.serialize({
    instructionDiscriminator: createTreasuryGovernanceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.realmConfig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realmAuthority,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.profit,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
