/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateMeSellProposal
 * @category generated
 */
export type CreateMeSellProposalInstructionArgs = {
  useDeny: boolean
}
/**
 * @category Instructions
 * @category CreateMeSellProposal
 * @category generated
 */
export const createMeSellProposalStruct = new beet.BeetArgsStruct<
  CreateMeSellProposalInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['useDeny', beet.bool],
  ],
  'CreateMeSellProposalInstructionArgs',
)
/**
 * Accounts required by the _createMeSellProposal_ instruction
 *
 * @property [_writable_] governance
 * @property [_writable_] realm
 * @property [] realmConfig
 * @property [_writable_] proposal
 * @property [_writable_] proposalTransactionAddress
 * @property [_writable_] tokenOwnerRecord
 * @property [] splGovernanceProgram
 * @property [] communityTokenMint
 * @property [_writable_, **signer**] payer
 * @property [] voterWeightRecord
 * @property [] clubData
 * @property [] treasuryData
 * @property [] treasury
 * @property [] vault
 * @property [] proposalMetadata
 * @property [] magicEdenData
 * @category Instructions
 * @category CreateMeSellProposal
 * @category generated
 */
export type CreateMeSellProposalInstructionAccounts = {
  governance: web3.PublicKey
  realm: web3.PublicKey
  realmConfig: web3.PublicKey
  proposal: web3.PublicKey
  proposalTransactionAddress: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  splGovernanceProgram: web3.PublicKey
  communityTokenMint: web3.PublicKey
  payer: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  clubData: web3.PublicKey
  treasuryData: web3.PublicKey
  treasury: web3.PublicKey
  vault: web3.PublicKey
  proposalMetadata: web3.PublicKey
  magicEdenData: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createMeSellProposalInstructionDiscriminator = [
  34, 123, 25, 237, 92, 233, 142, 207,
]

/**
 * Creates a _CreateMeSellProposal_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateMeSellProposal
 * @category generated
 */
export function createCreateMeSellProposalInstruction(
  accounts: CreateMeSellProposalInstructionAccounts,
  args: CreateMeSellProposalInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = createMeSellProposalStruct.serialize({
    instructionDiscriminator: createMeSellProposalInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realmConfig,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalTransactionAddress,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.communityTokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
