/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  TreasuryRolesDto,
  treasuryRolesDtoBeet,
} from '../types/TreasuryRolesDto.js'

/**
 * @category Instructions
 * @category CreateTreasury
 * @category generated
 */
export type CreateTreasuryInstructionArgs = {
  name: string
  chainId: string
  nftMaxVoterWeight: beet.COption<beet.bignum>
  roleDtos: TreasuryRolesDto[]
}
/**
 * @category Instructions
 * @category CreateTreasury
 * @category generated
 */
export const createTreasuryStruct = new beet.FixableBeetArgsStruct<
  CreateTreasuryInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['name', beet.utf8String],
    ['chainId', beet.utf8String],
    ['nftMaxVoterWeight', beet.coption(beet.u64)],
    ['roleDtos', beet.array(treasuryRolesDtoBeet)],
  ],
  'CreateTreasuryInstructionArgs',
)
/**
 * Accounts required by the _createTreasury_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [_writable_] treasury
 * @property [_writable_] treasuryData
 * @property [_writable_] profit
 * @property [] memberData
 * @property [_writable_] clubData
 * @property [_writable_] vaultData
 * @property [_writable_] vault
 * @property [_writable_] financialRecord
 * @property [] realm
 * @property [] splGovernance
 * @property [] tokenOwnerRecord
 * @category Instructions
 * @category CreateTreasury
 * @category generated
 */
export type CreateTreasuryInstructionAccounts = {
  payer: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  profit: web3.PublicKey
  memberData: web3.PublicKey
  clubData: web3.PublicKey
  vaultData: web3.PublicKey
  vault: web3.PublicKey
  financialRecord: web3.PublicKey
  realm: web3.PublicKey
  splGovernance: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createTreasuryInstructionDiscriminator = [
  254, 98, 217, 51, 25, 88, 140, 45,
]

/**
 * Creates a _CreateTreasury_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateTreasury
 * @category generated
 */
export function createCreateTreasuryInstruction(
  accounts: CreateTreasuryInstructionAccounts,
  args: CreateTreasuryInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = createTreasuryStruct.serialize({
    instructionDiscriminator: createTreasuryInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.profit,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vaultData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.financialRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.splGovernance,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
