/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * @category Instructions
 * @category CreateClubProposal
 * @category generated
 */
export type CreateClubProposalInstructionArgs = {
  chainId: string
  useDeny: boolean
  offeredAmount: beet.bignum
  wantedAmount: beet.bignum
  action: number
  dedicatedTaker: beet.COption<web3.PublicKey>
}
/**
 * @category Instructions
 * @category CreateClubProposal
 * @category generated
 */
export const createClubProposalStruct = new beet.FixableBeetArgsStruct<
  CreateClubProposalInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['chainId', beet.utf8String],
    ['useDeny', beet.bool],
    ['offeredAmount', beet.u64],
    ['wantedAmount', beet.u64],
    ['action', beet.u8],
    ['dedicatedTaker', beet.coption(beetSolana.publicKey)],
  ],
  'CreateClubProposalInstructionArgs',
)
/**
 * Accounts required by the _createClubProposal_ instruction
 *
 * @property [_writable_] governance
 * @property [_writable_] realm
 * @property [] governanceAuthority
 * @property [] realmConfig
 * @property [_writable_] proposal
 * @property [_writable_] proposalTransactionAddress
 * @property [_writable_] tokenOwnerRecord
 * @property [] splGovernanceProgram
 * @property [] communityTokenMint
 * @property [_writable_, **signer**] payer
 * @property [] voterWeightRecord
 * @property [_writable_] offer
 * @property [_writable_] makerOfferedTokens
 * @property [_writable_] escrowedWantedTokens
 * @property [] makerWantedAuthority
 * @property [] makerOfferedAuthority
 * @property [] treasuryData
 * @property [] proposalMetadata
 * @property [] clubData
 * @property [] wantedTokensMint
 * @category Instructions
 * @category CreateClubProposal
 * @category generated
 */
export type CreateClubProposalInstructionAccounts = {
  governance: web3.PublicKey
  realm: web3.PublicKey
  governanceAuthority: web3.PublicKey
  realmConfig: web3.PublicKey
  proposal: web3.PublicKey
  proposalTransactionAddress: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  splGovernanceProgram: web3.PublicKey
  communityTokenMint: web3.PublicKey
  payer: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  offer: web3.PublicKey
  makerOfferedTokens: web3.PublicKey
  escrowedWantedTokens: web3.PublicKey
  makerWantedAuthority: web3.PublicKey
  makerOfferedAuthority: web3.PublicKey
  treasuryData: web3.PublicKey
  proposalMetadata: web3.PublicKey
  clubData: web3.PublicKey
  wantedTokensMint: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createClubProposalInstructionDiscriminator = [
  90, 9, 139, 80, 245, 53, 100, 67,
]

/**
 * Creates a _CreateClubProposal_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateClubProposal
 * @category generated
 */
export function createCreateClubProposalInstruction(
  accounts: CreateClubProposalInstructionAccounts,
  args: CreateClubProposalInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = createClubProposalStruct.serialize({
    instructionDiscriminator: createClubProposalInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.governanceAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.realmConfig,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalTransactionAddress,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.communityTokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.offer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.makerOfferedTokens,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.escrowedWantedTokens,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.makerWantedAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.makerOfferedAuthority,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.wantedTokensMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
