/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category CreateTransferProposal
 * @category generated
 */
export type CreateTransferProposalInstructionArgs = {
  useDeny: boolean
  transferAmount: beet.bignum
}
/**
 * @category Instructions
 * @category CreateTransferProposal
 * @category generated
 */
export const createTransferProposalStruct = new beet.BeetArgsStruct<
  CreateTransferProposalInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['useDeny', beet.bool],
    ['transferAmount', beet.u64],
  ],
  'CreateTransferProposalInstructionArgs',
)
/**
 * Accounts required by the _createTransferProposal_ instruction
 *
 * @property [_writable_] governance
 * @property [_writable_] realm
 * @property [] realmConfig
 * @property [_writable_] proposal
 * @property [_writable_] proposalTransactionAddress
 * @property [_writable_] tokenOwnerRecord
 * @property [] splGovernanceProgram
 * @property [] communityTokenMint
 * @property [_writable_, **signer**] payer
 * @property [] voterWeightRecord
 * @property [_writable_] treasury
 * @property [] treasuryData
 * @property [] proposalMetadata
 * @property [] clubData
 * @property [] offer
 * @property [] destination
 * @property [] treasuryToken
 * @category Instructions
 * @category CreateTransferProposal
 * @category generated
 */
export type CreateTransferProposalInstructionAccounts = {
  governance: web3.PublicKey
  realm: web3.PublicKey
  realmConfig: web3.PublicKey
  proposal: web3.PublicKey
  proposalTransactionAddress: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  splGovernanceProgram: web3.PublicKey
  communityTokenMint: web3.PublicKey
  payer: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  proposalMetadata: web3.PublicKey
  clubData: web3.PublicKey
  offer: web3.PublicKey
  destination: web3.PublicKey
  treasuryToken: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const createTransferProposalInstructionDiscriminator = [
  20, 226, 232, 169, 80, 233, 217, 179,
]

/**
 * Creates a _CreateTransferProposal_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateTransferProposal
 * @category generated
 */
export function createCreateTransferProposalInstruction(
  accounts: CreateTransferProposalInstructionAccounts,
  args: CreateTransferProposalInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = createTransferProposalStruct.serialize({
    instructionDiscriminator: createTransferProposalInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realmConfig,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalTransactionAddress,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.communityTokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.offer,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.destination,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryToken,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
