/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ExecuteMeBuyNow
 * @category generated
 */
export type ExecuteMeBuyNowInstructionArgs = {
  data1: Uint8Array
  data2: Uint8Array
  data3: Uint8Array
}
/**
 * @category Instructions
 * @category ExecuteMeBuyNow
 * @category generated
 */
export const executeMeBuyNowStruct = new beet.FixableBeetArgsStruct<
  ExecuteMeBuyNowInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['data1', beet.bytes],
    ['data2', beet.bytes],
    ['data3', beet.bytes],
  ],
  'ExecuteMeBuyNowInstructionArgs',
)
/**
 * Accounts required by the _executeMeBuyNow_ instruction
 *
 * @property [_writable_, **signer**] payer
 * @property [] clubData
 * @property [_writable_] treasury
 * @property [] treasuryData
 * @property [] escrowProgram
 * @property [_writable_] offer
 * @property [_writable_] magicEdenAccountsHolder
 * @property [_writable_] sellersWallet
 * @property [] magicEdenExerchina
 * @property [_writable_] magicEdenEscrowedToken
 * @property [] magicEdenEscrowedTokenMint
 * @property [] magicEdenEscrowedTokenMetadata
 * @property [_writable_] magicEdenState1
 * @property [_writable_] escrowedWantedToken
 * @property [_writable_] autExer
 * @property [] e8cExer
 * @property [_writable_] expoitExer
 * @property [_writable_] magicEdenState2
 * @property [_writable_] magicEdenState3
 * @property [] onebwExer
 * @property [] associatedTokenProgram
 * @property [] magicEden
 * @property [_writable_] unqEscrowToken
 * @property [_writable_] account13
 * @property [_writable_] account15
 * @category Instructions
 * @category ExecuteMeBuyNow
 * @category generated
 */
export type ExecuteMeBuyNowInstructionAccounts = {
  payer: web3.PublicKey
  clubData: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  escrowProgram: web3.PublicKey
  offer: web3.PublicKey
  magicEdenAccountsHolder: web3.PublicKey
  sellersWallet: web3.PublicKey
  magicEdenExerchina: web3.PublicKey
  magicEdenEscrowedToken: web3.PublicKey
  magicEdenEscrowedTokenMint: web3.PublicKey
  magicEdenEscrowedTokenMetadata: web3.PublicKey
  magicEdenState1: web3.PublicKey
  escrowedWantedToken: web3.PublicKey
  autExer: web3.PublicKey
  e8cExer: web3.PublicKey
  expoitExer: web3.PublicKey
  magicEdenState2: web3.PublicKey
  magicEdenState3: web3.PublicKey
  onebwExer: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  magicEden: web3.PublicKey
  unqEscrowToken: web3.PublicKey
  account13: web3.PublicKey
  account15: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const executeMeBuyNowInstructionDiscriminator = [
  162, 181, 44, 226, 192, 42, 168, 74,
]

/**
 * Creates a _ExecuteMeBuyNow_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ExecuteMeBuyNow
 * @category generated
 */
export function createExecuteMeBuyNowInstruction(
  accounts: ExecuteMeBuyNowInstructionAccounts,
  args: ExecuteMeBuyNowInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = executeMeBuyNowStruct.serialize({
    instructionDiscriminator: executeMeBuyNowInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.escrowProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.offer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenAccountsHolder,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.sellersWallet,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenExerchina,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenEscrowedToken,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenEscrowedTokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenEscrowedTokenMetadata,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenState1,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.escrowedWantedToken,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.autExer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.e8cExer,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.expoitExer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenState2,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEdenState3,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.onebwExer,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.magicEden,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.unqEscrowToken,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.account13,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.account15,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
