/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ExecuteProposal
 * @category generated
 */
export const executeProposalStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ExecuteProposalInstructionArgs',
)
/**
 * Accounts required by the _executeProposal_ instruction
 *
 * @property [_writable_] governance
 * @property [_writable_] proposal
 * @property [_writable_] proposalTransaction
 * @property [] splGovernanceProgram
 * @property [_writable_, **signer**] payer
 * @property [_writable_] proposalMetadata
 * @property [_writable_] treasury
 * @property [_writable_] treasuryData
 * @property [_writable_] clubData
 * @category Instructions
 * @category ExecuteProposal
 * @category generated
 */
export type ExecuteProposalInstructionAccounts = {
  governance: web3.PublicKey
  proposal: web3.PublicKey
  proposalTransaction: web3.PublicKey
  splGovernanceProgram: web3.PublicKey
  payer: web3.PublicKey
  proposalMetadata: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  clubData: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const executeProposalInstructionDiscriminator = [
  186, 60, 116, 133, 108, 128, 111, 28,
]

/**
 * Creates a _ExecuteProposal_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ExecuteProposal
 * @category generated
 */
export function createExecuteProposalInstruction(
  accounts: ExecuteProposalInstructionAccounts,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = executeProposalStruct.serialize({
    instructionDiscriminator: executeProposalInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalTransaction,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
