/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ExecuteSellPermissionTransaction
 * @category generated
 */
export const executeSellPermissionTransactionStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ExecuteSellPermissionTransactionInstructionArgs',
)
/**
 * Accounts required by the _executeSellPermissionTransaction_ instruction
 *
 * @property [_writable_] governance
 * @property [_writable_] realm
 * @property [_writable_] realmConfig
 * @property [_writable_] proposal
 * @property [_writable_] proposalTransaction
 * @property [] splGovernanceProgram
 * @property [_writable_] tokenOwnerRecord
 * @property [_writable_] voterWeightRecord
 * @property [_writable_, **signer**] payer
 * @property [_writable_] proposalMetadata
 * @property [] clubData
 * @property [_writable_] treasuryData
 * @property [] memberData
 * @property [] clubProgram
 * @property [_writable_] spcGovernance
 * @property [] spcGovernedAccount
 * @category Instructions
 * @category ExecuteSellPermissionTransaction
 * @category generated
 */
export type ExecuteSellPermissionTransactionInstructionAccounts = {
  governance: web3.PublicKey
  realm: web3.PublicKey
  realmConfig: web3.PublicKey
  proposal: web3.PublicKey
  proposalTransaction: web3.PublicKey
  splGovernanceProgram: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  payer: web3.PublicKey
  proposalMetadata: web3.PublicKey
  clubData: web3.PublicKey
  treasuryData: web3.PublicKey
  memberData: web3.PublicKey
  clubProgram: web3.PublicKey
  spcGovernance: web3.PublicKey
  spcGovernedAccount: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const executeSellPermissionTransactionInstructionDiscriminator = [
  200, 20, 99, 155, 57, 193, 91, 59,
]

/**
 * Creates a _ExecuteSellPermissionTransaction_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ExecuteSellPermissionTransaction
 * @category generated
 */
export function createExecuteSellPermissionTransactionInstruction(
  accounts: ExecuteSellPermissionTransactionInstructionAccounts,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = executeSellPermissionTransactionStruct.serialize({
    instructionDiscriminator:
      executeSellPermissionTransactionInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.realmConfig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalTransaction,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clubProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.spcGovernance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.spcGovernedAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
