/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category ExecuteUpdateGovernanceConfig
 * @category generated
 */
export const executeUpdateGovernanceConfigStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'ExecuteUpdateGovernanceConfigInstructionArgs',
)
/**
 * Accounts required by the _executeUpdateGovernanceConfig_ instruction
 *
 * @property [] clubData
 * @property [] realm
 * @property [_writable_] governance
 * @property [_writable_] proposal
 * @property [_writable_] proposalMetadata
 * @property [] treasury
 * @property [_writable_] treasuryData
 * @property [_writable_] proposalTransaction
 * @property [] splGovernanceProgram
 * @category Instructions
 * @category ExecuteUpdateGovernanceConfig
 * @category generated
 */
export type ExecuteUpdateGovernanceConfigInstructionAccounts = {
  clubData: web3.PublicKey
  realm: web3.PublicKey
  governance: web3.PublicKey
  proposal: web3.PublicKey
  proposalMetadata: web3.PublicKey
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  proposalTransaction: web3.PublicKey
  splGovernanceProgram: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const executeUpdateGovernanceConfigInstructionDiscriminator = [
  165, 2, 117, 3, 50, 235, 179, 56,
]

/**
 * Creates a _ExecuteUpdateGovernanceConfig_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category ExecuteUpdateGovernanceConfig
 * @category generated
 */
export function createExecuteUpdateGovernanceConfigInstruction(
  accounts: ExecuteUpdateGovernanceConfigInstructionAccounts,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = executeUpdateGovernanceConfigStruct.serialize({
    instructionDiscriminator:
      executeUpdateGovernanceConfigInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.realm,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalTransaction,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
