/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InitializeStakingReward
 * @category generated
 */
export const initializeStakingRewardStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'InitializeStakingRewardInstructionArgs',
)
/**
 * Accounts required by the _initializeStakingReward_ instruction
 *
 * @property [_writable_] clubUnqTokens
 * @property [] unqMint
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category InitializeStakingReward
 * @category generated
 */
export type InitializeStakingRewardInstructionAccounts = {
  clubUnqTokens: web3.PublicKey
  unqMint: web3.PublicKey
  payer: web3.PublicKey
  rent?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const initializeStakingRewardInstructionDiscriminator = [
  30, 24, 220, 2, 25, 117, 42, 162,
]

/**
 * Creates a _InitializeStakingReward_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category InitializeStakingReward
 * @category generated
 */
export function createInitializeStakingRewardInstruction(
  accounts: InitializeStakingRewardInstructionAccounts,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = initializeStakingRewardStruct.serialize({
    instructionDiscriminator: initializeStakingRewardInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.clubUnqTokens,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.unqMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
