/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category InsertTransaction
 * @category generated
 */
export type InsertTransactionInstructionArgs = {
  data: Uint8Array[]
  signerIndexes: beet.COption<number[][]>
}
/**
 * @category Instructions
 * @category InsertTransaction
 * @category generated
 */
export const insertTransactionStruct = new beet.FixableBeetArgsStruct<
  InsertTransactionInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['data', beet.array(beet.bytes)],
    ['signerIndexes', beet.coption(beet.array(beet.array(beet.u32)))],
  ],
  'InsertTransactionInstructionArgs',
)
/**
 * Accounts required by the _insertTransaction_ instruction
 *
 * @property [] splGovernanceProgram
 * @property [_writable_] governance
 * @property [_writable_] proposal
 * @property [_writable_] proposalMetadata
 * @property [] treasuryData
 * @property [_writable_] proposalTransaction
 * @property [_writable_] tokenOwnerRecord
 * @property [] communityTokenMint
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category InsertTransaction
 * @category generated
 */
export type InsertTransactionInstructionAccounts = {
  splGovernanceProgram: web3.PublicKey
  governance: web3.PublicKey
  proposal: web3.PublicKey
  proposalMetadata: web3.PublicKey
  treasuryData: web3.PublicKey
  proposalTransaction: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  communityTokenMint: web3.PublicKey
  payer: web3.PublicKey
  rent?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const insertTransactionInstructionDiscriminator = [
  106, 8, 35, 192, 19, 26, 140, 38,
]

/**
 * Creates a _InsertTransaction_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category InsertTransaction
 * @category generated
 */
export function createInsertTransactionInstruction(
  accounts: InsertTransactionInstructionAccounts,
  args: InsertTransactionInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = insertTransactionStruct.serialize({
    instructionDiscriminator: insertTransactionInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.splGovernanceProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.governance,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposal,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalMetadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.proposalTransaction,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.communityTokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
