/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category LeaveClub
 * @category generated
 */
export const leaveClubStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */
}>(
  [['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)]],
  'LeaveClubInstructionArgs',
)
/**
 * Accounts required by the _leaveClub_ instruction
 *
 * @property [_writable_] realm
 * @property [_writable_] clubData
 * @property [_writable_] memberData
 * @property [_writable_] recipientMemberData
 * @property [_writable_] recipient
 * @property [_writable_] voterWeightRecord
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category LeaveClub
 * @category generated
 */
export type LeaveClubInstructionAccounts = {
  realm: web3.PublicKey
  clubData: web3.PublicKey
  memberData: web3.PublicKey
  recipientMemberData: web3.PublicKey
  recipient: web3.PublicKey
  voterWeightRecord: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const leaveClubInstructionDiscriminator = [
  174, 49, 33, 51, 161, 252, 0, 3,
]

/**
 * Creates a _LeaveClub_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category LeaveClub
 * @category generated
 */
export function createLeaveClubInstruction(
  accounts: LeaveClubInstructionAccounts,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = leaveClubStruct.serialize({
    instructionDiscriminator: leaveClubInstructionDiscriminator,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.realm,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.recipientMemberData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.recipient,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.voterWeightRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
