/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { ReservedRights, reservedRightsBeet } from '../types/ReservedRights.js'

/**
 * @category Instructions
 * @category ReserveRights
 * @category generated
 */
export type ReserveRightsInstructionArgs = {
  reservedRights: ReservedRights
}
/**
 * @category Instructions
 * @category ReserveRights
 * @category generated
 */
export const reserveRightsStruct = new beet.FixableBeetArgsStruct<
  ReserveRightsInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['reservedRights', reservedRightsBeet],
  ],
  'ReserveRightsInstructionArgs',
)
/**
 * Accounts required by the _reserveRights_ instruction
 *
 * @property [] clubData
 * @property [_writable_] treasuryData
 * @property [] memberData
 * @property [**signer**] payer
 * @category Instructions
 * @category ReserveRights
 * @category generated
 */
export type ReserveRightsInstructionAccounts = {
  clubData: web3.PublicKey
  treasuryData: web3.PublicKey
  memberData: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const reserveRightsInstructionDiscriminator = [
  55, 179, 63, 81, 50, 195, 14, 146,
]

/**
 * Creates a _ReserveRights_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category ReserveRights
 * @category generated
 */
export function createReserveRightsInstruction(
  accounts: ReserveRightsInstructionAccounts,
  args: ReserveRightsInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = reserveRightsStruct.serialize({
    instructionDiscriminator: reserveRightsInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: false,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
