/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { SupportType, supportTypeBeet } from '../types/SupportType.js'

/**
 * @category Instructions
 * @category SupportClub
 * @category generated
 */
export type SupportClubInstructionArgs = {
  supportType: SupportType
}
/**
 * @category Instructions
 * @category SupportClub
 * @category generated
 */
export const supportClubStruct = new beet.FixableBeetArgsStruct<
  SupportClubInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['supportType', supportTypeBeet],
  ],
  'SupportClubInstructionArgs',
)
/**
 * Accounts required by the _supportClub_ instruction
 *
 * @property [_writable_] memberData
 * @property [_writable_] fundraiseConfig
 * @property [_writable_] treasuryData
 * @property [] clubData
 * @property [_writable_] treasury
 * @property [_writable_] financialRecord
 * @property [_writable_, **signer**] payer
 * @property [] tokenOwnerRecord
 * @category Instructions
 * @category SupportClub
 * @category generated
 */
export type SupportClubInstructionAccounts = {
  memberData: web3.PublicKey
  fundraiseConfig: web3.PublicKey
  treasuryData: web3.PublicKey
  clubData: web3.PublicKey
  treasury: web3.PublicKey
  financialRecord: web3.PublicKey
  payer: web3.PublicKey
  tokenOwnerRecord: web3.PublicKey
  tokenProgram?: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const supportClubInstructionDiscriminator = [
  248, 12, 44, 204, 62, 167, 205, 162,
]

/**
 * Creates a _SupportClub_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SupportClub
 * @category generated
 */
export function createSupportClubInstruction(
  accounts: SupportClubInstructionAccounts,
  args: SupportClubInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = supportClubStruct.serialize({
    instructionDiscriminator: supportClubInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.memberData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.fundraiseConfig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasury,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.financialRecord,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.tokenOwnerRecord,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
