/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UnstakeTokens
 * @category generated
 */
export type UnstakeTokensInstructionArgs = {
  stakeIndex: number
  stakeOption: number
}
/**
 * @category Instructions
 * @category UnstakeTokens
 * @category generated
 */
export const unstakeTokensStruct = new beet.BeetArgsStruct<
  UnstakeTokensInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['stakeIndex', beet.u32],
    ['stakeOption', beet.u8],
  ],
  'UnstakeTokensInstructionArgs',
)
/**
 * Accounts required by the _unstakeTokens_ instruction
 *
 * @property [_writable_] clubData
 * @property [] memberData
 * @property [_writable_] stakeConfig
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category UnstakeTokens
 * @category generated
 */
export type UnstakeTokensInstructionAccounts = {
  clubData: web3.PublicKey
  memberData: web3.PublicKey
  stakeConfig: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const unstakeTokensInstructionDiscriminator = [
  58, 119, 215, 143, 203, 223, 32, 86,
]

/**
 * Creates a _UnstakeTokens_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UnstakeTokens
 * @category generated
 */
export function createUnstakeTokensInstruction(
  accounts: UnstakeTokensInstructionAccounts,
  args: UnstakeTokensInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = unstakeTokensStruct.serialize({
    instructionDiscriminator: unstakeTokensInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.clubData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.stakeConfig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
