/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  CustomAllocation,
  customAllocationBeet,
} from '../types/CustomAllocation.js'

/**
 * @category Instructions
 * @category UpdateAllocation
 * @category generated
 */
export type UpdateAllocationInstructionArgs = {
  equal: beet.COption<beet.bignum>
  customAllocations: beet.COption<CustomAllocation[]>
  removeAllocation: beet.COption<CustomAllocation[]>
  newCap: beet.COption<beet.bignum>
}
/**
 * @category Instructions
 * @category UpdateAllocation
 * @category generated
 */
export const updateAllocationStruct = new beet.FixableBeetArgsStruct<
  UpdateAllocationInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['equal', beet.coption(beet.u64)],
    ['customAllocations', beet.coption(beet.array(customAllocationBeet))],
    ['removeAllocation', beet.coption(beet.array(customAllocationBeet))],
    ['newCap', beet.coption(beet.u64)],
  ],
  'UpdateAllocationInstructionArgs',
)
/**
 * Accounts required by the _updateAllocation_ instruction
 *
 * @property [] clubData
 * @property [_writable_] treasuryData
 * @property [] memberData
 * @property [_writable_] fundraiseConfig
 * @property [_writable_, **signer**] payer
 * @category Instructions
 * @category UpdateAllocation
 * @category generated
 */
export type UpdateAllocationInstructionAccounts = {
  clubData: web3.PublicKey
  treasuryData: web3.PublicKey
  memberData: web3.PublicKey
  fundraiseConfig: web3.PublicKey
  payer: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const updateAllocationInstructionDiscriminator = [
  173, 2, 145, 33, 101, 74, 233, 115,
]

/**
 * Creates a _UpdateAllocation_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UpdateAllocation
 * @category generated
 */
export function createUpdateAllocationInstruction(
  accounts: UpdateAllocationInstructionAccounts,
  args: UpdateAllocationInstructionArgs,
  programId = new web3.PublicKey('UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe'),
) {
  const [data] = updateAllocationStruct.serialize({
    instructionDiscriminator: updateAllocationInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.clubData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.treasuryData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.memberData,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.fundraiseConfig,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
