/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
import { AdminConfig, adminConfigBeet } from '../types/AdminConfig.js'
import {
  FundraiseFeeConfig,
  fundraiseFeeConfigBeet,
} from '../types/FundraiseFeeConfig.js'
import { OtcFeeConfig, otcFeeConfigBeet } from '../types/OtcFeeConfig.js'

/**
 * Arguments used to create {@link Admins}
 * @category Accounts
 * @category generated
 */
export type AdminsArgs = {
  feeWallet: web3.PublicKey
  feePercentage: number
  adminConfigs: AdminConfig[]
  fundraiseFeeConfigs: FundraiseFeeConfig[]
  otcFeeConfigs: OtcFeeConfig[]
}

export const adminsDiscriminator = [4, 143, 168, 175, 239, 59, 78, 140]
/**
 * Holds the data for the {@link Admins} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Admins implements AdminsArgs {
  private constructor(
    readonly feeWallet: web3.PublicKey,
    readonly feePercentage: number,
    readonly adminConfigs: AdminConfig[],
    readonly fundraiseFeeConfigs: FundraiseFeeConfig[],
    readonly otcFeeConfigs: OtcFeeConfig[],
  ) {}

  /**
   * Creates a {@link Admins} instance from the provided args.
   */
  static fromArgs(args: AdminsArgs) {
    return new Admins(
      args.feeWallet,
      args.feePercentage,
      args.adminConfigs,
      args.fundraiseFeeConfigs,
      args.otcFeeConfigs,
    )
  }

  /**
   * Deserializes the {@link Admins} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [Admins, number] {
    return Admins.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Admins} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<Admins> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Admins account at ${address}`)
    }
    return Admins.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, adminsBeet)
  }

  /**
   * Deserializes the {@link Admins} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Admins, number] {
    return adminsBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Admins} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return adminsBeet.serialize({
      accountDiscriminator: adminsDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Admins} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: AdminsArgs) {
    const instance = Admins.fromArgs(args)
    return adminsBeet.toFixedFromValue({
      accountDiscriminator: adminsDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Admins} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: AdminsArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Admins.byteSize(args),
      commitment,
    )
  }

  /**
   * Returns a readable version of {@link Admins} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      feeWallet: this.feeWallet.toBase58(),
      feePercentage: this.feePercentage,
      adminConfigs: this.adminConfigs,
      fundraiseFeeConfigs: this.fundraiseFeeConfigs,
      otcFeeConfigs: this.otcFeeConfigs,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const adminsBeet = new beet.FixableBeetStruct<
  Admins,
  AdminsArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['feeWallet', beetSolana.publicKey],
    ['feePercentage', beet.u32],
    ['adminConfigs', beet.array(adminConfigBeet)],
    ['fundraiseFeeConfigs', beet.array(fundraiseFeeConfigBeet)],
    ['otcFeeConfigs', beet.array(otcFeeConfigBeet)],
  ],
  Admins.fromArgs,
  'Admins',
)
