/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link ClubVaultData}
 * @category Accounts
 * @category generated
 */
export type ClubVaultDataArgs = {
  chainId: string
}

export const clubVaultDataDiscriminator = [10, 92, 209, 182, 94, 49, 77, 151]
/**
 * Holds the data for the {@link ClubVaultData} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class ClubVaultData implements ClubVaultDataArgs {
  private constructor(readonly chainId: string) {}

  /**
   * Creates a {@link ClubVaultData} instance from the provided args.
   */
  static fromArgs(args: ClubVaultDataArgs) {
    return new ClubVaultData(args.chainId)
  }

  /**
   * Deserializes the {@link ClubVaultData} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [ClubVaultData, number] {
    return ClubVaultData.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link ClubVaultData} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<ClubVaultData> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find ClubVaultData account at ${address}`)
    }
    return ClubVaultData.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, clubVaultDataBeet)
  }

  /**
   * Deserializes the {@link ClubVaultData} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [ClubVaultData, number] {
    return clubVaultDataBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link ClubVaultData} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return clubVaultDataBeet.serialize({
      accountDiscriminator: clubVaultDataDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link ClubVaultData} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: ClubVaultDataArgs) {
    const instance = ClubVaultData.fromArgs(args)
    return clubVaultDataBeet.toFixedFromValue({
      accountDiscriminator: clubVaultDataDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link ClubVaultData} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: ClubVaultDataArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      ClubVaultData.byteSize(args),
      commitment,
    )
  }

  /**
   * Returns a readable version of {@link ClubVaultData} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      chainId: this.chainId,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const clubVaultDataBeet = new beet.FixableBeetStruct<
  ClubVaultData,
  ClubVaultDataArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['chainId', beet.utf8String],
  ],
  ClubVaultData.fromArgs,
  'ClubVaultData',
)
