/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import {
  MagicEdenInstruction,
  magicEdenInstructionBeet,
} from '../types/MagicEdenInstruction.js'

/**
 * Arguments used to create {@link MagicEdenData}
 * @category Accounts
 * @category generated
 */
export type MagicEdenDataArgs = {
  instruction: MagicEdenInstruction
  data: Uint8Array[]
  accounts: web3.PublicKey[]
}

export const magicEdenDataDiscriminator = [233, 60, 229, 1, 20, 248, 167, 121]
/**
 * Holds the data for the {@link MagicEdenData} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MagicEdenData implements MagicEdenDataArgs {
  private constructor(
    readonly instruction: MagicEdenInstruction,
    readonly data: Uint8Array[],
    readonly accounts: web3.PublicKey[],
  ) {}

  /**
   * Creates a {@link MagicEdenData} instance from the provided args.
   */
  static fromArgs(args: MagicEdenDataArgs) {
    return new MagicEdenData(args.instruction, args.data, args.accounts)
  }

  /**
   * Deserializes the {@link MagicEdenData} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [MagicEdenData, number] {
    return MagicEdenData.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MagicEdenData} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<MagicEdenData> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find MagicEdenData account at ${address}`)
    }
    return MagicEdenData.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, magicEdenDataBeet)
  }

  /**
   * Deserializes the {@link MagicEdenData} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [MagicEdenData, number] {
    return magicEdenDataBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link MagicEdenData} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return magicEdenDataBeet.serialize({
      accountDiscriminator: magicEdenDataDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MagicEdenData} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: MagicEdenDataArgs) {
    const instance = MagicEdenData.fromArgs(args)
    return magicEdenDataBeet.toFixedFromValue({
      accountDiscriminator: magicEdenDataDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MagicEdenData} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: MagicEdenDataArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MagicEdenData.byteSize(args),
      commitment,
    )
  }

  /**
   * Returns a readable version of {@link MagicEdenData} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      instruction:
        'MagicEdenInstruction.' + MagicEdenInstruction[this.instruction],
      data: this.data,
      accounts: this.accounts,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const magicEdenDataBeet = new beet.FixableBeetStruct<
  MagicEdenData,
  MagicEdenDataArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['instruction', magicEdenInstructionBeet],
    ['data', beet.array(beet.bytes)],
    ['accounts', beet.array(beetSolana.publicKey)],
  ],
  MagicEdenData.fromArgs,
  'MagicEdenData',
)
