/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link MaxVoterWeightRecord}
 * @category Accounts
 * @category generated
 */
export type MaxVoterWeightRecordArgs = {
  realm: web3.PublicKey
  governingTokenMint: web3.PublicKey
  maxVoterWeight: beet.bignum
  maxVoterWeightExpiry: beet.COption<beet.bignum>
  reserved: number[] /* size: 8 */
}

export const maxVoterWeightRecordDiscriminator = [
  157, 95, 242, 151, 16, 98, 26, 118,
]
/**
 * Holds the data for the {@link MaxVoterWeightRecord} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class MaxVoterWeightRecord implements MaxVoterWeightRecordArgs {
  private constructor(
    readonly realm: web3.PublicKey,
    readonly governingTokenMint: web3.PublicKey,
    readonly maxVoterWeight: beet.bignum,
    readonly maxVoterWeightExpiry: beet.COption<beet.bignum>,
    readonly reserved: number[] /* size: 8 */,
  ) {}

  /**
   * Creates a {@link MaxVoterWeightRecord} instance from the provided args.
   */
  static fromArgs(args: MaxVoterWeightRecordArgs) {
    return new MaxVoterWeightRecord(
      args.realm,
      args.governingTokenMint,
      args.maxVoterWeight,
      args.maxVoterWeightExpiry,
      args.reserved,
    )
  }

  /**
   * Deserializes the {@link MaxVoterWeightRecord} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [MaxVoterWeightRecord, number] {
    return MaxVoterWeightRecord.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link MaxVoterWeightRecord} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<MaxVoterWeightRecord> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(
        `Unable to find MaxVoterWeightRecord account at ${address}`,
      )
    }
    return MaxVoterWeightRecord.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, maxVoterWeightRecordBeet)
  }

  /**
   * Deserializes the {@link MaxVoterWeightRecord} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [MaxVoterWeightRecord, number] {
    return maxVoterWeightRecordBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link MaxVoterWeightRecord} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return maxVoterWeightRecordBeet.serialize({
      accountDiscriminator: maxVoterWeightRecordDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link MaxVoterWeightRecord} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: MaxVoterWeightRecordArgs) {
    const instance = MaxVoterWeightRecord.fromArgs(args)
    return maxVoterWeightRecordBeet.toFixedFromValue({
      accountDiscriminator: maxVoterWeightRecordDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link MaxVoterWeightRecord} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: MaxVoterWeightRecordArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      MaxVoterWeightRecord.byteSize(args),
      commitment,
    )
  }

  /**
   * Returns a readable version of {@link MaxVoterWeightRecord} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      realm: this.realm.toBase58(),
      governingTokenMint: this.governingTokenMint.toBase58(),
      maxVoterWeight: (() => {
        const x = <{ toNumber: () => number }>this.maxVoterWeight
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      maxVoterWeightExpiry: this.maxVoterWeightExpiry,
      reserved: this.reserved,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const maxVoterWeightRecordBeet = new beet.FixableBeetStruct<
  MaxVoterWeightRecord,
  MaxVoterWeightRecordArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['realm', beetSolana.publicKey],
    ['governingTokenMint', beetSolana.publicKey],
    ['maxVoterWeight', beet.u64],
    ['maxVoterWeightExpiry', beet.coption(beet.u64)],
    ['reserved', beet.uniformFixedSizeArray(beet.u8, 8)],
  ],
  MaxVoterWeightRecord.fromArgs,
  'MaxVoterWeightRecord',
)
