/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'

/**
 * Arguments used to create {@link NftVoteRecord}
 * @category Accounts
 * @category generated
 */
export type NftVoteRecordArgs = {
  proposal: web3.PublicKey
  nftMint: web3.PublicKey
  governingTokenOwner: web3.PublicKey
}

export const nftVoteRecordDiscriminator = [137, 6, 55, 139, 251, 126, 254, 99]
/**
 * Holds the data for the {@link NftVoteRecord} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class NftVoteRecord implements NftVoteRecordArgs {
  private constructor(
    readonly proposal: web3.PublicKey,
    readonly nftMint: web3.PublicKey,
    readonly governingTokenOwner: web3.PublicKey,
  ) {}

  /**
   * Creates a {@link NftVoteRecord} instance from the provided args.
   */
  static fromArgs(args: NftVoteRecordArgs) {
    return new NftVoteRecord(
      args.proposal,
      args.nftMint,
      args.governingTokenOwner,
    )
  }

  /**
   * Deserializes the {@link NftVoteRecord} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [NftVoteRecord, number] {
    return NftVoteRecord.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link NftVoteRecord} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<NftVoteRecord> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find NftVoteRecord account at ${address}`)
    }
    return NftVoteRecord.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, nftVoteRecordBeet)
  }

  /**
   * Deserializes the {@link NftVoteRecord} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [NftVoteRecord, number] {
    return nftVoteRecordBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link NftVoteRecord} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return nftVoteRecordBeet.serialize({
      accountDiscriminator: nftVoteRecordDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link NftVoteRecord}
   */
  static get byteSize() {
    return nftVoteRecordBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link NftVoteRecord} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      NftVoteRecord.byteSize,
      commitment,
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link NftVoteRecord} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === NftVoteRecord.byteSize
  }

  /**
   * Returns a readable version of {@link NftVoteRecord} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      proposal: this.proposal.toBase58(),
      nftMint: this.nftMint.toBase58(),
      governingTokenOwner: this.governingTokenOwner.toBase58(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const nftVoteRecordBeet = new beet.BeetStruct<
  NftVoteRecord,
  NftVoteRecordArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['proposal', beetSolana.publicKey],
    ['nftMint', beetSolana.publicKey],
    ['governingTokenOwner', beetSolana.publicKey],
  ],
  NftVoteRecord.fromArgs,
  'NftVoteRecord',
)
