/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link TransferProfitData}
 * @category Accounts
 * @category generated
 */
export type TransferProfitDataArgs = {
  treasury: web3.PublicKey
  treasuryData: web3.PublicKey
  treasuryToken: web3.PublicKey
  proposal: web3.PublicKey
  slotExpiry: beet.bignum
}

export const transferProfitDataDiscriminator = [
  123, 200, 55, 211, 6, 236, 34, 243,
]
/**
 * Holds the data for the {@link TransferProfitData} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class TransferProfitData implements TransferProfitDataArgs {
  private constructor(
    readonly treasury: web3.PublicKey,
    readonly treasuryData: web3.PublicKey,
    readonly treasuryToken: web3.PublicKey,
    readonly proposal: web3.PublicKey,
    readonly slotExpiry: beet.bignum,
  ) {}

  /**
   * Creates a {@link TransferProfitData} instance from the provided args.
   */
  static fromArgs(args: TransferProfitDataArgs) {
    return new TransferProfitData(
      args.treasury,
      args.treasuryData,
      args.treasuryToken,
      args.proposal,
      args.slotExpiry,
    )
  }

  /**
   * Deserializes the {@link TransferProfitData} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [TransferProfitData, number] {
    return TransferProfitData.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link TransferProfitData} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<TransferProfitData> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find TransferProfitData account at ${address}`)
    }
    return TransferProfitData.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, transferProfitDataBeet)
  }

  /**
   * Deserializes the {@link TransferProfitData} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [TransferProfitData, number] {
    return transferProfitDataBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link TransferProfitData} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return transferProfitDataBeet.serialize({
      accountDiscriminator: transferProfitDataDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link TransferProfitData}
   */
  static get byteSize() {
    return transferProfitDataBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link TransferProfitData} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      TransferProfitData.byteSize,
      commitment,
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link TransferProfitData} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === TransferProfitData.byteSize
  }

  /**
   * Returns a readable version of {@link TransferProfitData} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      treasury: this.treasury.toBase58(),
      treasuryData: this.treasuryData.toBase58(),
      treasuryToken: this.treasuryToken.toBase58(),
      proposal: this.proposal.toBase58(),
      slotExpiry: (() => {
        const x = <{ toNumber: () => number }>this.slotExpiry
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const transferProfitDataBeet = new beet.BeetStruct<
  TransferProfitData,
  TransferProfitDataArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['treasury', beetSolana.publicKey],
    ['treasuryData', beetSolana.publicKey],
    ['treasuryToken', beetSolana.publicKey],
    ['proposal', beetSolana.publicKey],
    ['slotExpiry', beet.u64],
  ],
  TransferProfitData.fromArgs,
  'TransferProfitData',
)
