/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link WithdrawalData}
 * @category Accounts
 * @category generated
 */
export type WithdrawalDataArgs = {
  realm: web3.PublicKey
  clubData: web3.PublicKey
  treasury: web3.PublicKey
  proposal: web3.PublicKey
  fundraiseNumber: number
  withdrawalAmount: beet.bignum
  amountWithdrawn: beet.bignum
  totalFinancialPower: beet.bignum
  withdrawalMint: web3.PublicKey
  proposalCreatedAt: beet.bignum
}

export const withdrawalDataDiscriminator = [
  200, 132, 73, 123, 101, 219, 141, 36,
]
/**
 * Holds the data for the {@link WithdrawalData} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class WithdrawalData implements WithdrawalDataArgs {
  private constructor(
    readonly realm: web3.PublicKey,
    readonly clubData: web3.PublicKey,
    readonly treasury: web3.PublicKey,
    readonly proposal: web3.PublicKey,
    readonly fundraiseNumber: number,
    readonly withdrawalAmount: beet.bignum,
    readonly amountWithdrawn: beet.bignum,
    readonly totalFinancialPower: beet.bignum,
    readonly withdrawalMint: web3.PublicKey,
    readonly proposalCreatedAt: beet.bignum,
  ) {}

  /**
   * Creates a {@link WithdrawalData} instance from the provided args.
   */
  static fromArgs(args: WithdrawalDataArgs) {
    return new WithdrawalData(
      args.realm,
      args.clubData,
      args.treasury,
      args.proposal,
      args.fundraiseNumber,
      args.withdrawalAmount,
      args.amountWithdrawn,
      args.totalFinancialPower,
      args.withdrawalMint,
      args.proposalCreatedAt,
    )
  }

  /**
   * Deserializes the {@link WithdrawalData} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0,
  ): [WithdrawalData, number] {
    return WithdrawalData.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link WithdrawalData} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig,
  ): Promise<WithdrawalData> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig,
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find WithdrawalData account at ${address}`)
    }
    return WithdrawalData.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      'UNQc364EDzKQqfSW1Fnhfam2fvsFGVdVqg77kpBqRSe',
    ),
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, withdrawalDataBeet)
  }

  /**
   * Deserializes the {@link WithdrawalData} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [WithdrawalData, number] {
    return withdrawalDataBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link WithdrawalData} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return withdrawalDataBeet.serialize({
      accountDiscriminator: withdrawalDataDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link WithdrawalData}
   */
  static get byteSize() {
    return withdrawalDataBeet.byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link WithdrawalData} data from rent
   *
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    connection: web3.Connection,
    commitment?: web3.Commitment,
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      WithdrawalData.byteSize,
      commitment,
    )
  }

  /**
   * Determines if the provided {@link Buffer} has the correct byte size to
   * hold {@link WithdrawalData} data.
   */
  static hasCorrectByteSize(buf: Buffer, offset = 0) {
    return buf.byteLength - offset === WithdrawalData.byteSize
  }

  /**
   * Returns a readable version of {@link WithdrawalData} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      realm: this.realm.toBase58(),
      clubData: this.clubData.toBase58(),
      treasury: this.treasury.toBase58(),
      proposal: this.proposal.toBase58(),
      fundraiseNumber: this.fundraiseNumber,
      withdrawalAmount: (() => {
        const x = <{ toNumber: () => number }>this.withdrawalAmount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      amountWithdrawn: (() => {
        const x = <{ toNumber: () => number }>this.amountWithdrawn
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      totalFinancialPower: (() => {
        const x = <{ toNumber: () => number }>this.totalFinancialPower
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      withdrawalMint: this.withdrawalMint.toBase58(),
      proposalCreatedAt: (() => {
        const x = <{ toNumber: () => number }>this.proposalCreatedAt
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const withdrawalDataBeet = new beet.BeetStruct<
  WithdrawalData,
  WithdrawalDataArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['realm', beetSolana.publicKey],
    ['clubData', beetSolana.publicKey],
    ['treasury', beetSolana.publicKey],
    ['proposal', beetSolana.publicKey],
    ['fundraiseNumber', beet.u32],
    ['withdrawalAmount', beet.u64],
    ['amountWithdrawn', beet.u64],
    ['totalFinancialPower', beet.u64],
    ['withdrawalMint', beetSolana.publicKey],
    ['proposalCreatedAt', beet.i64],
  ],
  WithdrawalData.fromArgs,
  'WithdrawalData',
)
