/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category BuyAsset
 * @category generated
 */
export type BuyAssetInstructionArgs = {
  timestamp: beet.bignum
  exemplars: number
}
/**
 * @category Instructions
 * @category BuyAsset
 * @category generated
 */
export const buyAssetStruct = new beet.BeetArgsStruct<
  BuyAssetInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['timestamp', beet.u64],
    ['exemplars', beet.u32],
  ],
  'BuyAssetInstructionArgs',
)
/**
 * Accounts required by the _buyAsset_ instruction
 *
 * @property [] associatedTokenProgram
 * @property [] clock
 * @property [_writable_, **signer**] authority
 * @property [_writable_] asset
 * @property [_writable_] assetMint
 * @property [_writable_] buyerTransferVault
 * @property [] acceptedMint
 * @property [_writable_] payment
 * @property [_writable_] paymentVault
 * @property [_writable_] buyerMintedTokenVault
 * @category Instructions
 * @category BuyAsset
 * @category generated
 */
export type BuyAssetInstructionAccounts = {
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  rent?: web3.PublicKey
  clock: web3.PublicKey
  authority: web3.PublicKey
  asset: web3.PublicKey
  assetMint: web3.PublicKey
  buyerTransferVault: web3.PublicKey
  acceptedMint: web3.PublicKey
  payment: web3.PublicKey
  paymentVault: web3.PublicKey
  buyerMintedTokenVault: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const buyAssetInstructionDiscriminator = [
  197, 37, 177, 1, 180, 23, 175, 98,
]

/**
 * Creates a _BuyAsset_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category BuyAsset
 * @category generated
 */
export function createBuyAssetInstruction(
  accounts: BuyAssetInstructionAccounts,
  args: BuyAssetInstructionArgs,
  programId = new web3.PublicKey(
    '84KfPcJAZhNSLMmSzgx3kDx3FfKfS3WK5u8FF8zks18S',
  ),
) {
  const [data] = buyAssetStruct.serialize({
    instructionDiscriminator: buyAssetInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.clock,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.asset,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.assetMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerTransferVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.acceptedMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.payment,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.paymentVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerMintedTokenVault,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
