/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category EditAssetPrice
 * @category generated
 */
export type EditAssetPriceInstructionArgs = {
  tokenPrice: number
}
/**
 * @category Instructions
 * @category EditAssetPrice
 * @category generated
 */
export const editAssetPriceStruct = new beet.BeetArgsStruct<
  EditAssetPriceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['tokenPrice', beet.u32],
  ],
  'EditAssetPriceInstructionArgs',
)
/**
 * Accounts required by the _editAssetPrice_ instruction
 *
 * @property [_writable_, **signer**] authority
 * @property [_writable_] asset
 * @category Instructions
 * @category EditAssetPrice
 * @category generated
 */
export type EditAssetPriceInstructionAccounts = {
  authority: web3.PublicKey
  asset: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const editAssetPriceInstructionDiscriminator = [
  36, 117, 167, 200, 35, 59, 247, 66,
]

/**
 * Creates a _EditAssetPrice_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category EditAssetPrice
 * @category generated
 */
export function createEditAssetPriceInstruction(
  accounts: EditAssetPriceInstructionAccounts,
  args: EditAssetPriceInstructionArgs,
  programId = new web3.PublicKey(
    '84KfPcJAZhNSLMmSzgx3kDx3FfKfS3WK5u8FF8zks18S',
  ),
) {
  const [data] = editAssetPriceStruct.serialize({
    instructionDiscriminator: editAssetPriceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.asset,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
