/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category UseAsset
 * @category generated
 */
export type UseAssetInstructionArgs = {
  exemplars: number
}
/**
 * @category Instructions
 * @category UseAsset
 * @category generated
 */
export const useAssetStruct = new beet.BeetArgsStruct<
  UseAssetInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['exemplars', beet.u32],
  ],
  'UseAssetInstructionArgs',
)
/**
 * Accounts required by the _useAsset_ instruction
 *
 * @property [] associatedTokenProgram
 * @property [_writable_, **signer**] authority
 * @property [_writable_] asset
 * @property [_writable_] assetMint
 * @property [_writable_] buyerMintedTokenVault
 * @category Instructions
 * @category UseAsset
 * @category generated
 */
export type UseAssetInstructionAccounts = {
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  associatedTokenProgram: web3.PublicKey
  rent?: web3.PublicKey
  authority: web3.PublicKey
  asset: web3.PublicKey
  assetMint: web3.PublicKey
  buyerMintedTokenVault: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const useAssetInstructionDiscriminator = [
  114, 253, 6, 49, 141, 203, 167, 238,
]

/**
 * Creates a _UseAsset_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category UseAsset
 * @category generated
 */
export function createUseAssetInstruction(
  accounts: UseAssetInstructionAccounts,
  args: UseAssetInstructionArgs,
  programId = new web3.PublicKey(
    '84KfPcJAZhNSLMmSzgx3kDx3FfKfS3WK5u8FF8zks18S',
  ),
) {
  const [data] = useAssetStruct.serialize({
    instructionDiscriminator: useAssetInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.associatedTokenProgram,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.asset,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.assetMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerMintedTokenVault,
      isWritable: true,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
