/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import * as beet from '@metaplex-foundation/beet'
import { AdminPermission, adminPermissionBeet } from './AdminPermission.js'
import { AdminStatus, adminStatusBeet } from './AdminStatus.js'
export type AdminConfig = {
  admin: web3.PublicKey
  permissions: AdminPermission[]
  status: AdminStatus
}

/**
 * @category userTypes
 * @category generated
 */
export const adminConfigBeet = new beet.FixableBeetArgsStruct<AdminConfig>(
  [
    ['admin', beetSolana.publicKey],
    ['permissions', beet.array(adminPermissionBeet)],
    ['status', adminStatusBeet],
  ],
  'AdminConfig',
)
