/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
/**
 * @category enums
 * @category generated
 */
export enum ClubAction {
  CastVote,
  CreateDiscussionProposal,
  CreateTreasuryGovernance,
  CreateWithdrawalGovernance,
  CreateTransferGovernance,
  CreateP2PProposal,
  CreateWithdrawalProposal,
  CreateTransferProposal,
  CreateMeProposal,
  SignOffProposal,
  CancelProposal,
  AllowMember,
  CancelP2POffer,
  CancelInvitation,
  Fundraise,
  Distribute,
  SupportClub,
  UpdateMember,
  InitializeStaking,
  StakeTokens,
  CreateFinancialOffer,
  AcceptFinancialOffer,
  CreateSolseaProposal,
  CreateChangeClubConfigGovernance,
  UpdateGovernanceConfig,
  UpdateRoleConfig,
  AddReservedRights,
  UpdateAllocation,
  AddReservedRightsToSelf,
  CanLeave,
}

/**
 * @category userTypes
 * @category generated
 */
export const clubActionBeet = beet.fixedScalarEnum(
  ClubAction,
) as beet.FixedSizeBeet<ClubAction, ClubAction>
