/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { TradedRight, tradedRightBeet } from './TradedRight.js'
export type DepositRecord = {
  accumulatedAmount: beet.bignum
  fundraiseIndex: number
  depositedAt: beet.bignum
  currentFundraiseDeposit: beet.bignum
  tradedRight: beet.COption<TradedRight[]>
}

/**
 * @category userTypes
 * @category generated
 */
export const depositRecordBeet = new beet.FixableBeetArgsStruct<DepositRecord>(
  [
    ['accumulatedAmount', beet.u64],
    ['fundraiseIndex', beet.u32],
    ['depositedAt', beet.i64],
    ['currentFundraiseDeposit', beet.u64],
    ['tradedRight', beet.coption(beet.array(tradedRightBeet))],
  ],
  'DepositRecord',
)
