/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { GovernanceType, governanceTypeBeet } from './GovernanceType.js'
import { SellPermission, sellPermissionBeet } from './SellPermission.js'
export type GovernanceDto = {
  governanceType: GovernanceType
  maxVotingTime: number
  voteThresholdPercentage: number
  sellPermission: beet.COption<SellPermission>
}

/**
 * @category userTypes
 * @category generated
 */
export const governanceDtoBeet = new beet.FixableBeetArgsStruct<GovernanceDto>(
  [
    ['governanceType', governanceTypeBeet],
    ['maxVotingTime', beet.u32],
    ['voteThresholdPercentage', beet.u8],
    ['sellPermission', beet.coption(sellPermissionBeet)],
  ],
  'GovernanceDto',
)
