/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import {
  VoteThresholdPercentage,
  voteThresholdPercentageBeet,
} from './VoteThresholdPercentage.js'
import { VoteTipping, voteTippingBeet } from './VoteTipping.js'
export type GovernanceConfig = {
  voteThresholdPercentage: VoteThresholdPercentage
  minCommunityWeightToCreateProposal: beet.bignum
  minTransactionHoldUpTime: number
  maxVotingTime: number
  voteTipping: VoteTipping
  proposalCoolOffTime: number
  minCouncilWeightToCreateProposal: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const governanceConfigBeet =
  new beet.FixableBeetArgsStruct<GovernanceConfig>(
    [
      ['voteThresholdPercentage', voteThresholdPercentageBeet],
      ['minCommunityWeightToCreateProposal', beet.u64],
      ['minTransactionHoldUpTime', beet.u32],
      ['maxVotingTime', beet.u32],
      ['voteTipping', voteTippingBeet],
      ['proposalCoolOffTime', beet.u32],
      ['minCouncilWeightToCreateProposal', beet.u64],
    ],
    'GovernanceConfig',
  )
