/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type IndividualRight = {
  memberPubkey: web3.PublicKey
  rightPercentage: number
  amountOfRights: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const individualRightBeet = new beet.BeetArgsStruct<IndividualRight>(
  [
    ['memberPubkey', beetSolana.publicKey],
    ['rightPercentage', beet.u32],
    ['amountOfRights', beet.u64],
  ],
  'IndividualRight',
)
