/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { Rarity, rarityBeet } from './Rarity.js'
export type NftStakeRecord = {
  nftOwner: web3.PublicKey
  tokenAccount: web3.PublicKey
  tokenMint: web3.PublicKey
  stakedNft: web3.PublicKey
  rarity: Rarity
  hasClaimed: boolean
  unstakePeriodEnd: beet.COption<beet.bignum>
}

/**
 * @category userTypes
 * @category generated
 */
export const nftStakeRecordBeet =
  new beet.FixableBeetArgsStruct<NftStakeRecord>(
    [
      ['nftOwner', beetSolana.publicKey],
      ['tokenAccount', beetSolana.publicKey],
      ['tokenMint', beetSolana.publicKey],
      ['stakedNft', beetSolana.publicKey],
      ['rarity', rarityBeet],
      ['hasClaimed', beet.bool],
      ['unstakePeriodEnd', beet.coption(beet.i64)],
    ],
    'NftStakeRecord',
  )
