/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type Order = {
  amount: beet.bignum
  mint: web3.PublicKey
  slot: beet.bignum
  createdAt: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const orderBeet = new beet.BeetArgsStruct<Order>(
  [
    ['amount', beet.u64],
    ['mint', beetSolana.publicKey],
    ['slot', beet.u64],
    ['createdAt', beet.i64],
  ],
  'Order',
)
