/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
/**
 * @category enums
 * @category generated
 */
export enum ProposalType {
  BuyP2P,
  SellP2P,
  BuyNowMagicEden,
  SellMagicEden,
  TransferFunds,
  Discussion,
  Withdrawal,
  SellSolsea,
  BuySolsea,
  UpdateGovernanceConfig,
  UpdateRoleConfig,
  AddSellPermission,
}

/**
 * @category userTypes
 * @category generated
 */
export const proposalTypeBeet = beet.fixedScalarEnum(
  ProposalType,
) as beet.FixedSizeBeet<ProposalType, ProposalType>
