/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'
export type SellPermission = {
  from: beet.bignum
  to: beet.bignum
  quorumMinimum: number
  decimal: number
  governance: web3.PublicKey
}

/**
 * @category userTypes
 * @category generated
 */
export const sellPermissionBeet = new beet.BeetArgsStruct<SellPermission>(
  [
    ['from', beet.u64],
    ['to', beet.u64],
    ['quorumMinimum', beet.u8],
    ['decimal', beet.u16],
    ['governance', beetSolana.publicKey],
  ],
  'SellPermission',
)
