/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { GovernanceConfig, governanceConfigBeet } from './GovernanceConfig.js'
export type SetGovCfgDto = {
  config: GovernanceConfig[]
  seeds: Uint8Array[][]
}

/**
 * @category userTypes
 * @category generated
 */
export const setGovCfgDtoBeet = new beet.FixableBeetArgsStruct<SetGovCfgDto>(
  [
    ['config', beet.array(governanceConfigBeet)],
    ['seeds', beet.array(beet.array(beet.bytes))],
  ],
  'SetGovCfgDto',
)
