/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import { TreasuryAction, treasuryActionBeet } from './TreasuryAction.js'
export type TreasuryRoleConfig = {
  name: string
  roleWeight: beet.bignum
  treasuryActions: TreasuryAction[]
  membersCount: number
  isDefault: boolean
}

/**
 * @category userTypes
 * @category generated
 */
export const treasuryRoleConfigBeet =
  new beet.FixableBeetArgsStruct<TreasuryRoleConfig>(
    [
      ['name', beet.utf8String],
      ['roleWeight', beet.u64],
      ['treasuryActions', beet.array(treasuryActionBeet)],
      ['membersCount', beet.u32],
      ['isDefault', beet.bool],
    ],
    'TreasuryRoleConfig',
  )
