/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type UpdateRoleWeight = {
  role: string
  currentWeight: beet.bignum
  updateWeight: beet.bignum
}

/**
 * @category userTypes
 * @category generated
 */
export const updateRoleWeightBeet =
  new beet.FixableBeetArgsStruct<UpdateRoleWeight>(
    [
      ['role', beet.utf8String],
      ['currentWeight', beet.u64],
      ['updateWeight', beet.u64],
    ],
    'UpdateRoleWeight',
  )
