/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type UpdateMemberDto = {
  isMember: beet.COption<boolean>
  status: beet.COption<number>
  role: beet.COption<string>
}

/**
 * @category userTypes
 * @category generated
 */
export const updateMemberDtoBeet =
  new beet.FixableBeetArgsStruct<UpdateMemberDto>(
    [
      ['isMember', beet.coption(beet.bool)],
      ['status', beet.coption(beet.u8)],
      ['role', beet.coption(beet.utf8String)],
    ],
    'UpdateMemberDto',
  )
