/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type UpdateGovernanceConfigInput = {
  newQuorums: Uint8Array
  seeds: Uint8Array[][]
  newVotingTime: beet.COption<number>
}

/**
 * @category userTypes
 * @category generated
 */
export const updateGovernanceConfigInputBeet =
  new beet.FixableBeetArgsStruct<UpdateGovernanceConfigInput>(
    [
      ['newQuorums', beet.bytes],
      ['seeds', beet.array(beet.array(beet.bytes))],
      ['newVotingTime', beet.coption(beet.u32)],
    ],
    'UpdateGovernanceConfigInput',
  )
